server:
  port: 9901
spring:
  datasource:
    url: jdbc:mysql://localhost/cs544_project
    username: root
    password: "@Adoustar4"
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
  level:
    root: DEBUG